@startuml
title PA4 - e-invoice

participant "Seller Bank "  as ITS_Bank
participant "Seller IT"  as IT_Seller

participant "Buyer EUBW " as IT_Buyer
participant "Buyer Verif.System " as ITB_ERP
participant "Buyer Bank "  as ITB_Bank
participant "Buyer PSP" as ITB_PSP

participant "Auth.Pers EUDIW" as B_EUDI

== PA4. Pre-requisite==
alt "Onboarding the Seller BU1"
IT_Seller<-> IT_Buyer: part of KYC /KYS
end
alt "Onboarding by Bank-Seller PA3"
IT_Seller<-> ITS_Bank: onboarding process
end
alt "Onboarding by Bank-Buyer PA3"
IT_Buyer<-> ITB_Bank: onboarding process
end
alt "e-Invoice send SC5"
IT_Seller<-> IT_Buyer: order service/products
IT_Seller<-> IT_Buyer: exchange the invoice (directyl/over portal)
IT_Buyer <-> IT_Buyer: e-invoice  integrity check
end

== Step 1. PA4 - SCA (case)  ==
alt "PA4. SCA - Issuing ?"
IT_Buyer<->ITB_Bank : start the SCA Onboarding
note left
who make this ?
end note
ITB_Bank<->IT_Buyer: additionally information((SignatoryRights, EU POA)
ITB_Bank<->B_EUDI: onboard the person & issue the SCA
end
== Step 2. PA4 - Request to pay ==
IT_Buyer-> ITB_ERP : notify the verification of the invoice
ITB_ERP->ITB_ERP: verifies the invoice
ITB_ERP-> ITB_PSP: initiate payment (card / IBAN)
ITB_PSP-> ITB_Bank: fill the payment
ITB_Bank->ITB_Bank: process payment
ITB_Bank->B_EUDI: request authorization
ITS_Bank<->ITB_Bank: execute payment
ITB_Bank->ITB_PSP : payment confirmation
ITB_PSP->ITB_Bank: payment reconciliation
== Step 2. PA4 - TAX information ==

== Step 3. PA4 - eReciept ==
ITS_Bank->IT_Seller : notification receive payments
IT_Seller -> IT_Buyer : send eReceipt
@enduml